const products = [
  {
    id: 1,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 2,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 3,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 4,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 5,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 6,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 7,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 8,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 9,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 12,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 11,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 23,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 45,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 65,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 76,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 78,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 19,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 98,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 1,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 89,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 42,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 18,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
  {
    id: 26,
    image: "https://via.placeholder.com/300",
    title: "Football Field Pencil Case",
    price: 19.0,
    rating: 5,
    shopName: "efratul",
  },
  {
    id: 275,
    image: "https://via.placeholder.com/150",
    title: "Soccer Ball Necklace",
    price: 50.79,
    rating: 4,
    shopName: "DreamBeadsDovi",
  },
];

export default products;
